version: '2'
services:
  dev:
    build:
      context: .
    image: samples/laravel
    container_name: laravel-samples
    hostname: laravel-samples.dev
    volumes:
      - ./src:/var/www/html
    environment:
      - DB_NAME=tuneis
      - DB_USER=root
      - DB_PASS=root
      - DB_HOST=mysql-server.dev
      - WP_DEBUG=0
    network_mode: bridge